version: "3"
services:
    web:
        build:
          context: .
          dockerfile: DataImporter.Web/Dockerfile
        image: dataimporterweb
        container_name: web
        restart: unless-stopped
        tty: true
        env_file: 
            - web.env
        ports:
            - "8000:80"
        volumes:
            - dataimporter-data:/app/Logs
    
    worker:
        build:
          context: .
          dockerfile: DataImporter.Worker/Dockerfile
        image: dataimporterworker
        restart: unless-stopped
        tty: true
        env_file: 
            - importer.env
        volumes:
            - dataimporter-data:/app/Logs

volumes:
    dataimporter-data: 
        external: true
  